### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Ason93** [Cambricon/triton-linalg#20]
GLIBCXX_3.4.26
      /home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/command/editable_wheel.py:286: SetuptoolsDeprecationWarning: Customization incompatible with editable install
      !!
      
              ********************************************************************************
                              Traceback (most recent call last):
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 292, in _safely_run
                  return self.run_command(cmd_name)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
                  self.distribution.run_command(command)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/dist.py", line 948, in run_command
                  super().run_command(command)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
                  cmd_obj.run()
                File "<string>", line 296, in run
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
                  self.distribution.run_command(command)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/dist.py", line 948, in run_command
                  super().run_command(command)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
                  cmd_obj.run()
                File "<string>", line 333, in run
                File "<string>", line 347, in build_extension
                File "<string>", line 224, in get_thirdparty_packages
                File "<string>", line 196, in open_url
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/urllib/request.py", line 216, in urlopen
                  return opener.open(url, data, timeout)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/urllib/request.py", line 525, in open
                  response = meth(req, response)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/urllib/request.py", line 634, in http_response
                  response = self.parent.error(
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/urllib/request.py", line 563, in error
                  return self._call_chain(*args)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/urllib/request.py", line 496, in _call_chain
                  result = func(*args)
                File "/home/jinchengxiong/.conda/envs/triton_linalg/lib/python3.10/urllib/request.py", line 643, in http_error_default
                  raise HTTPError(req.full_url, code, msg, hdrs, fp)
              urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
      
      
                              If you are seeing this warning it is very likely that a setuptools
                              plugin or customization overrides the `build_py` command, without
                              taking into consideration how editable installs run build steps
                              starting from setuptools v64.0.0.
      
                              Plugin authors and developers relying on custom build steps are
                              encouraged to update their `build_py` implementation considering the
                              information about editable installs in
                              https://setuptools.pypa.io/en/latest/userguide/extension.html.
      
                              For the time being `setuptools` will silence this error and ignore
                              the faulty command, but this behaviour will change in future versions.
      
              ********************************************************************************

**Comment by hesse-x** [comment]
It appears that there is insufficient information to pinpoint this error. It seems that the failure to connect during the download of a certain component has led to the error. You might want to try retrying the process.

**Comment by Ason93** [comment]
Yes, I try a lot of times. It seems llvm-ed4e505c-ubuntu-x64.tar.gz couldn't be downloaded.
 writing manifest file '/tmp/pip-wheel-w5c48zma/.tmp-j4d1ajxh/triton.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-w5c48zma/.tmp-j4d1ajxh/triton-3.0.0.dist-info'
      creating /tmp/pip-wheel-w5c48zma/.tmp-j4d1ajxh/triton-3.0.0.dist-info/WHEEL
      running build_py
      running build_ext
      GLIBCXX_3.4.26
      downloading and extracting https://tritonlang.blob.core.windows.net/llvm-builds/llvm-ed4e505c-ubuntu-x64.tar.gz ...
      running build_ext
      GLIBCXX_3.4.26
      /usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      /usr/lib/python3.8/site-packages/setuptools/command/editable_wheel.py:286: SetuptoolsDeprecationWarning: Customization incompatible with editable install
      !!
      
              ********************************************************************************
                              Traceback (most recent call last):
                File "/usr/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 292, in _safely_run
                  return self.run_command(cmd_name)
                File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
                  self.distribution.run_command(command)
                File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
                  super().run_command(command)
                File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
                  cmd_obj.run()
                File "<string>", line 296, in run
                File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
                  self.distribution.run_command(command)
                File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
                  super().run_command(command)
                File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
                  cmd_obj.run()
                File "<string>", line 333, in run
                File "<string>", line 347, in build_extension
                File "<string>", line 224, in get_thirdparty_packages
                File "<string>", line 196, in open_url
                File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
                  return opener.open(url, data, timeout)
                File "/usr/lib/python3.8/urllib/request.py", line 531, in open
                  response = meth(req, response)
                File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
                  response = self.parent.error(
                File "/usr/lib/python3.8/urllib/request.py", line 569, in error
                  return self._call_chain(*args)
                File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
                  result = func(*args)
                File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
                  raise HTTPError(req.full_url, code, msg, hdrs, fp)
              urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
      
      
                              If you are seeing this warning it is very likely that a setuptools
                              plugin or customization overrides the `build_py` command, without
                              taking into consideration how editable installs run build steps
                              starting from setuptools v64.0.0.
      
                              Plugin authors and developers relying on custom build steps are
                              encouraged to update their `build_py` implementation considering the
                              information about editable installs in
                              https://setuptools.pypa.io/en/latest/userguide/extension.html.
      
                              For the time being `setuptools` will silence this error and ignore
                              the faulty command, but this behaviour will change in future versions.
      
              ********************************************************************************
      
      !!
        self._safely_run(name)
      Traceback (most recent call last):
        File "/usr/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 135, in run
          self._create_wheel_file(bdist_wheel)
        File "/usr/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 338, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/usr/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 261, in _run_build_commands
          self._run_build_subcommands()
        File "/usr/lib/python3.8/site-packages/setuptools/command/editable_wheel.py", line 288, in _run_build_subcommands
          self.run_command(name)
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 948, in run_command
          super().run_command(command)
        File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "<string>", line 333, in run
        File "<string>", line 347, in build_extension
        File "<string>", line 224, in get_thirdparty_packages
        File "<string>", line 196, in open_url
        File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
          return opener.open(url, data, timeout)
        File "/usr/lib/python3.8/urllib/request.py", line 531, in open
          response = meth(req, response)
        File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
          response = self.parent.error(
        File "/usr/lib/python3.8/urllib/request.py", line 569, in error
          return self._call_chain(*args)
        File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
          result = func(*args)
        File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
      /usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py:983: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `triton` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      downloading and extracting https://tritonlang.blob.core.windows.net/llvm-builds/llvm-ed4e505c-ubuntu-x64.tar.gz ...
      error: HTTP Error 409: Public access is not permitted on this storage account.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for triton
Failed to build triton
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (triton)

**Comment by hesse-x** [comment]
You can try downloading the LLVM package directly using your browser or manually via the command line from this URL: https://tritonlang.blob.core.windows.net/llvm-builds/llvm-ed4e505c-ubuntu-x64.tar.gz. After downloading, set up a local HTTP server and modify the download link for LLVM in the `triton/python/setup.py` file to point to your local HTTP server. This package is essential for compiling Triton itself, and the network connection on OpenAI's servers might indeed be less reliable.

**Comment by Ason93** [comment]
Maybe this link is invalid now
wget https://tritonlang.blob.core.windows.net/llvm-builds/llvm-ed4e505c-ubuntu-x64.tar.gz
--2024-08-21 10:32:31--  https://tritonlang.blob.core.windows.net/llvm-builds/llvm-ed4e505c-ubuntu-x64.tar.gz
Resolving tritonlang.blob.core.windows.net (tritonlang.blob.core.windows.net)... 20.47.62.100, 20.47.62.112, 20.47.62.60
Connecting to tritonlang.blob.core.windows.net (tritonlang.blob.core.windows.net)|20.47.62.100|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2024-08-21 10:32:32 ERROR 409: Public access is not permitted on this storage account..

**Comment by sethbrin** [comment]
Indeed, Triton has officially removed the prebuilt LLVM package. We will be upgrading Triton's dependencies in subsequent versions, as the upgrade involving LLVM may take some time. You can refer to the Triton [README description](https://github.com/triton-lang/triton/blob/6083043eb7a0722db6bd2ad8efc453300da74819/README.md?plain=1#L58) for instructions on compiling LLVM code.

**Comment by hesse-x** [comment]
It seems that the link has been restored. You can try again to see if you can download it now.
